// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDymUI0dEvQQv4ecNSduFXfbxZkR_7fu-c',
    appId: '1:528434728343:web:01cc0ee866bb7e003448d2',
    messagingSenderId: '528434728343',
    projectId: 'flutter-kutuphanem',
    authDomain: 'flutter-kutuphanem.firebaseapp.com',
    storageBucket: 'flutter-kutuphanem.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBjBeMiNPXRWjPb_07Y62XZbhYdhkApfs',
    appId: '1:528434728343:android:2a5a645896d756bb3448d2',
    messagingSenderId: '528434728343',
    projectId: 'flutter-kutuphanem',
    storageBucket: 'flutter-kutuphanem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHEWGo12suIa2IsPps1VNittlb8fk_p9k',
    appId: '1:528434728343:ios:61e6b5de9e07bfc43448d2',
    messagingSenderId: '528434728343',
    projectId: 'flutter-kutuphanem',
    storageBucket: 'flutter-kutuphanem.appspot.com',
    iosClientId: '528434728343-q094qmieut8pc1q6sklrbn9f788qlbrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.kutuphanem',
  );
}
